project:
  type: website
  output-dir: docs

website:
  title: "ShuoHang's Website "
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - github.qmd


format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

